"""add rejected at to signals

Revision ID: 21f850c64110
Revises: 5ce1a6975048
Create Date: 2026-03-06 21:22:02.780219

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21f850c64110"
down_revision: str | None = "5ce1a6975048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("signals", sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint("signals_strategy_id_fkey", "signals", type_="foreignkey")
    op.drop_constraint("signals_trade_id_fkey", "signals", type_="foreignkey")
    op.drop_constraint("signals_owner_id_fkey", "signals", type_="foreignkey")
    op.create_foreign_key(
        None, "signals", "strategies", ["strategy_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(None, "signals", "trades", ["trade_id"], ["id"], ondelete="SET NULL")
    op.create_foreign_key(None, "signals", "users", ["owner_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "signals", type_="foreignkey")
    op.drop_constraint(None, "signals", type_="foreignkey")
    op.drop_constraint(None, "signals", type_="foreignkey")
    op.create_foreign_key("signals_owner_id_fkey", "signals", "users", ["owner_id"], ["id"])
    op.create_foreign_key("signals_trade_id_fkey", "signals", "trades", ["trade_id"], ["id"])
    op.create_foreign_key(
        "signals_strategy_id_fkey", "signals", "strategies", ["strategy_id"], ["id"]
    )
    op.drop_column("signals", "rejected_at")
    # ### end Alembic commands ###
